export { GiscoreClient } from "./client";
export {
  openLoginPopup,
  exchangeSession,
  parseCallbackParams,
  createLoginHandler,
  type PopupLoginOptions,
  type LoginResult,
} from "./auth";
export type {
  GiscoreConfig,
  GiscoreData,
  Viewer,
  PaginationParams,
  ReactionContent,
  Author,
  ReactionGroup,
  PageInfo,
  Reply,
  Comment,
  DiscussionCategory,
  Discussion,
  DiscussionSearchResult,
  Repository,
  CreatedDiscussion,
  CreatedComment,
  CreatedReply,
  ToggleReactionResult,
  ToggleUpvoteResult,
  RepliesResult,
} from "./types";
